### ISSUE TITLE
BUG: Example is incorrect.

### ISSUE THREAD

**Issue by yardz** [Nexmo/nexmo-node-code-snippets#62]
The current example shows to use **voiceName** but when using it was not selecting the correct voice.

That way it does not work:
```js
nexmo.calls.talk.start(CALL_UUID, { text: TEXT, voiceName: 'Vitoria', loop: 0 }, (err, res) => {
  if(err) { console.error(err); }
  else {
      console.log(res);
  }
});
```

I investigated the CURL requests and saw that the parameter name is **voice_name**. I think it would be interesting or fix this bug (Nodejs) or update the example.

That way it works:
```js
nexmo.calls.talk.start(CALL_UUID, { text: TEXT, voice_name: 'Vitoria', loop: 0 }, (err, res) => {
  if(err) { console.error(err); }
  else {
      console.log(res);
  }
});
```

**Comment by AlexLakatos** [comment]
The node library just passes on the parameters to the API, so it's not a bug there. https://github.com/Nexmo/nexmo-node/blob/master/src/TalkResource.js#L36

I've opened #63 to update the code sample.

Thank you for opening the issue!
