### ISSUE TITLE
conversations is undefined

### ISSUE THREAD

**Issue by RajaBanerjee1** [Nexmo/nexmo-node-code-snippets#72]
nexmo.conversations.get(
                    ^

TypeError: Cannot read property 'get' of undefined

I know several calls have been made inbound and outbound. Is there a nexmo libraries version that I should be using ?

**Comment by AlexLakatos** [comment]
Yes, for conversations, users, channels, dispatch and applications you should be using the beta version of the node library.
`npm install nexmo@beta`
