### ISSUE TITLE
Nexmo Inbound Message Tracking

### ISSUE THREAD

**Issue by ankkit93** [Nexmo/nexmo-node-code-snippets#73]
The problem I am facing is that we are using a single nexmo number in multiple modules in our application. So, I'm not able to differentiate which application module response users sending to i.e. whether it is two-way-messaging, group messaging or campaign.
In my opinion.
1. If Nexmo gives the same Message-ID in users SMS response that is already generated while sending the SMS, it will help me to find corresponding message ID in my database application and help me to response to that corresponding message easily.
2. If Nexmo uses the webhook that I already set before to receive messages, user response use that webhook which uses before to send the message. Even after I override the webhook for the given number.

**Comment by AlexLakatos** [comment]
Hey @ankkit93, I'l try to address your suggestions and then offer some solutions.
1. Nexmo does not have access to the user device the SMS is sent from, so we can't add anything like that to the inbound webhook.
2. I'm afraid I don't understand exactly what you're proposing here. Can you please explain more?

In terms of solving your problem, I suggest keeping track of the last message you sent to that particular number in your DB, and then cross-referencing when you receive an SMS from that number. When you send an SMS, you can optionally include your own reference of up to 40 characters with the [`client-ref` field](https://developer.nexmo.com/api/sms#send-an-sms). So if you set that on the last message you sent to a number and tag it with things like `two-way-sms` or `campaign`, and save it in the database, when you receive an sms from that number, you can check the tag you associated with the last message you sent to that number. Hope this is helpful.
