### ISSUE TITLE
Cannot read property 'message_uuid' of null

### ISSUE THREAD

**Issue by kopi-kosong** [Nexmo/nexmo-node-code-snippets#78]
I am getting an error when trying whatapp js. 

 (err, data) => { console.log(data.message_uuid); }
                                    ^

TypeError: Cannot read property 'message_uuid' of null
    at C:\george\12.Apps\sendNexmoSMS\sendWhatapp.js:30:37
    at HttpClient.__parseResponse (C:\george\12.Apps\sendNexmoSMS\node_modules\nexmo\lib\HttpClient.js:232:9)
    at IncomingMessage.<anonymous> (C:\george\12.Apps\sendNexmoSMS\node_modules\nexmo\lib\HttpClient.js:141:19)
    at IncomingMessage.emit (events.js:328:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by AlexLakatos** [comment]
That's probably because of an error happening. Try replacing that with 
```(err, data) => {
    if (error) {
        console.log(error)
    } else {
        console.log(data.message_uuid); 
    }
}```

**Comment by kopi-kosong** [comment]
Alex, 

Thank you!!! after changing per your suggestion, i finally can see the error. 

{
  body: {
    type: 'https://www.nexmo.com/messages/Errors#InvalidParams',
    title: "Your request parameters didn't validate.",
    detail: 'Found errors validating 1 of your submitted parameters.',
    instance: 'db405d542048f2a68872a54563448edd',
    invalid_parameters: [ [Object] ]
  },
  headers: {
    date: 'Thu, 19 Mar 2020 01:41:44 GMT',
    'content-type': 'application/problem+json',
    'content-length': '315',
    connection: 'close',
    'set-cookie': [
      '__cfduid=d2bf53fcbb748b251b9fcb0684ee565781584582104; expires=Sat, 18-Apr-20 01:41:44 GMT; path=/; domain=.nexmo.com; HttpOnly; SameSite=Lax'
    ],
    'x-frame-options': 'deny',
    'x-xss-protection': '1; mode=block;',
    'strict-transport-security': 'max-age=31536000; includeSubdomains',
    'x-content-type-options': 'nosniff',
    'content-disposition': 'attachment; filename="api.txt"',
    'x-nexmo-trace-id': 'db405d542048f2a68872a54563448edd',
    'cf-cache-status': 'DYNAMIC',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    server: 'cloudflare',
    'cf-ray': '57637e277c1884b8-HKG'
  },
  statusCode: 400
}
